version: '3'
services:
  scraping:
    restart: always
    build:
      context: ./infra/scraping
      dockerfile: Dockerfile.dev
    working_dir: '/usr/src/app'
    env_file:
      - .env
    volumes:
      - ./src/scraping:/usr/src/app
    tty: true
    depends_on:
      db:
        condition: service_healthy
  db:
    restart: always
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql

volumes:
  db-store: