version: '3'
services:
  scraping:
    restart: always
    build:
      context: ./infra/scraping
      dockerfile: Dockerfile.dev
    working_dir: '/usr/src/app'
    env_file:
      - .env
    volumes:
      - ./src/scraping:/usr/src/app
    tty: true